
language: python

python: '3.6.2'

install: 
  - pip install -r requirements.txt
  - pip install coveralls

script:
  # - python test_web_app.py
  # - pytest
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=app


after_success: 
  - "coveralls"

